version: "3"
services:
  sqlDB:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mydevpassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
  
  api:
    depends_on:
      - sqlDB
    build:
      dockerfile: "./Dockerfile"
    ports:
      - "8080:80"
    environment:
      CONNECTION_STRING: "${CONNECTION_STRING}"