import "./globals.css";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import { MainComponent } from "./MainComponent";
import { HeaderComponent } from "./HeaderComponents";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <MainComponent>{children}</MainComponent>
      </body>
    </html>
  );
};

export default RootLayout;
