on:
  repository_dispatch:
    types: [submit_feedback]

permissions:
  contents: read
  issues: write 

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: ${{ github.event.client_payload.title }}
          NAME: ${{ github.event.client_payload.name }}
          EMAIL: ${{ github.event.client_payload.email }}
          BODY: ${{ github.event.client_payload.body }}
        with:
          filename: .github/feedback-issue-template.md
